name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Generate version
        id: version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $env:GITHUB_OUTPUT
          echo "DATE=$(Get-Date -Format 'yyyyMMdd')" >> $env:GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release
          compression-level: 9
      - name: Create Windows Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: windows-${{ steps.version.outputs.DATE }}-${{ steps.version.outputs.BUILD_NUMBER }}
          name: Windows Release ${{ steps.version.outputs.DATE }} Build ${{ steps.version.outputs.BUILD_NUMBER }}
          files: |
            build/windows/x64/runner/Release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - name: Generate version
        id: version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle
          compression-level: 9
      - name: Create Linux Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-${{ steps.version.outputs.DATE }}-${{ steps.version.outputs.BUILD_NUMBER }}
          name: Linux Release ${{ steps.version.outputs.DATE }} Build ${{ steps.version.outputs.BUILD_NUMBER }}
          files: build/linux/x64/release/bundle/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: Generate version
        id: version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release
          compression-level: 9
      - name: Create macOS Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: macos-${{ steps.version.outputs.DATE }}-${{ steps.version.outputs.BUILD_NUMBER }}
          name: macOS Release ${{ steps.version.outputs.DATE }} Build ${{ steps.version.outputs.BUILD_NUMBER }}
          files: build/macos/Build/Products/Release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk
      - name: Generate version
        id: version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
          compression-level: 9
      - name: Create Android Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-${{ steps.version.outputs.DATE }}-${{ steps.version.outputs.BUILD_NUMBER }}
          name: Android Release ${{ steps.version.outputs.DATE }} Build ${{ steps.version.outputs.BUILD_NUMBER }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-combined-release:
    needs: [build-and-release-windows, build-and-release-linux, build-and-release-macos, build-and-release-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate version number
        id: version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create ZIP archives
        run: |
          cd artifacts
          zip -r windows-release.zip windows-release/
          zip -r linux-release.zip linux-release/
          zip -r macos-release.zip macos-release/
      
      - name: Create Combined Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.version.outputs.DATE }}-${{ steps.version.outputs.BUILD_NUMBER }}
          name: Combined Release ${{ steps.version.outputs.DATE }} Build ${{ steps.version.outputs.BUILD_NUMBER }}
          draft: false
          prerelease: false
          files: |
            artifacts/windows-release.zip
            artifacts/linux-release.zip
            artifacts/macos-release.zip
            artifacts/android-release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 