name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.0)'
        required: false
        default: ''
      release_notes:
        description: 'Release notes'
        required: false
        default: 'Manual build triggered from GitHub Actions'

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./bdix_ftp_tester
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Install dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build windows
        run: flutter build windows --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: bdix_ftp_tester/build/windows/x64/runner/Release
          compression-level: 9

  build-and-release-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bdix_ftp_tester
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build linux
        run: flutter build linux --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: bdix_ftp_tester/build/linux/x64/release/bundle
          compression-level: 9

  build-and-release-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./bdix_ftp_tester
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build macOS
        run: flutter build macos --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: bdix_ftp_tester/build/macos/Build/Products/Release
          compression-level: 9

  build-and-release-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bdix_ftp_tester
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: bdix_ftp_tester/build/app/outputs/flutter-apk/app-release.apk
          compression-level: 9

  create-release:
    needs: [build-and-release-windows, build-and-release-linux, build-and-release-macos, build-and-release-android]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows-release/**
            artifacts/linux-release/**
            artifacts/macos-release/**
            artifacts/android-release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 